"""init_db

Revision ID: 1c66c9b4b20c
Revises: f19be21bc7ac
Create Date: 2026-02-09 11:04:59.920623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c66c9b4b20c'
down_revision: Union[str, Sequence[str], None] = 'f19be21bc7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('training_center_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('athletes_categorie_id_fkey'), 'athletes', type_='foreignkey')
    op.create_foreign_key(None, 'athletes', 'training_centers', ['training_center_id'], ['pk_id'])
    op.create_foreign_key(None, 'athletes', 'categories', ['categorie_id'], ['pk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'athletes', type_='foreignkey')
    op.drop_constraint(None, 'athletes', type_='foreignkey')
    op.create_foreign_key(op.f('athletes_categorie_id_fkey'), 'athletes', 'training_centers', ['categorie_id'], ['pk_id'])
    op.drop_column('athletes', 'training_center_id')
    # ### end Alembic commands ###
